### PR TITLE
chore: add PR template

### PR DESCRIPTION
**Pull request by peterwoodworth**
adds PR template

----

*By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license*

### CODE REVIEW

**Review by ryparker — COMMENTED** [review]
Is this supposed to be empty?

**Comment by peterwoodworth** [comment]
it isn't empty - there's a file there!

**Comment by ryparker** [comment]
I see the file but it doesn't look like there's any template stuff. Just a comment. Not sure if you forgot to commit the rest of it or if this is how it's supposed to be?

**Comment by peterwoodworth** [comment]
Yeah - it's identical to the PR template in the CDK repo https://github.com/aws/aws-cdk/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by ryparker** [comment]
Oh my bad.

**Review by ryparker — COMMENTED** [review]
👍🏻

**Review by ryparker — APPROVED** [review]

**Pull request merged**
